= ラボガイド: イベント駆動型Ansible入門
:doctype: book
:notoc:
:toc-title: Table of Contents
:nosectnums:
:icons: font

_イベント駆動型Ansibleの概念についての紹介と、Ansible Automation Platformで必要な認証情報を設定するためのガイドです。_

---

== ラボの概要

=== このラボ環境について

各対話型ラボ環境には、設定された時間制限（多くの場合60分）があり、アイドルタイムアウトが含まれる場合があります。環境がタイムアウトした場合、進捗は失われますが、いつでもラボを再開できます。

[IMPORTANT]
.Ansible Automation Platform (AAP) の認証情報
====
* **ユーザー名:** `admin`
* **パスワード:** `ansible123!`
====

[IMPORTANT]
.Gitea の認証情報
====
* **ユーザー名:** `student`
* **パスワード:** `learn_ansible`
====

---

== イベント駆動型Ansible入門

イベント駆動型Ansibleを使用すると、インフラストラクチャやアプリケーションのイベントへの対応をコード化でき、自動化の回復性と応答性を高めることができます。Automation Controllerが（Playbookを介して）応答を自動化するのに対し、イベント駆動型Ansibleは（Rulebookを介して）イベント自体の認識を自動化します。

Ansible Automation Platform (AAP) の最近のリリースでは、コンポーネントは統一されたUIに集約されています。イベント駆動型AnsibleとAutomation Controllerの統合は、**Automation Decisions**が**Automation Execution**のテンプレートを実行するために使用できる認証情報を作成することによって設定されます。

. **Ansible Automation Platformにログインします。** `AAP`タブをクリックし、`admin` / `ansible123!`の認証情報を使用してログインします。
. **UIを探索します。** ログイン後、**Automation Execution** (Automation Controller) と **Automation Decisions** (Event-Driven Ansible Controller) のメニューセクションがあることに注意してください。このラボを進める中で、これらのコンポーネントメニュー間を移動する必要があるかもしれません。
* **Automation Decisions:** イベントの条件が *Rulebook* で定義され、*Rulebook Activations* を介して有効化される場所です。
* **Automation Execution:** *アクション*がPlaybookを実行する *Templates* として定義される場所です。
. **Automation Decisions用の認証情報を作成します。** まず、2つのコンポーネントが通信できるように認証情報を作成する必要があります。**Automation Decisions** → **Infrastructure** → **Credentials**に移動し、**Create credential**ボタンをクリックします。
. **認証情報の詳細を入力します。** 以下の詳細でフォームに入力してください。
+
[cols="1,1,2a"]
|===
| キー | 値 | 備考

| *Name*
| `AAP`
|

| *Description*
| `Credential used to execute jobs from Automation Execution`
| `Automation Executionからジョブを実行するために使用される認証情報`

| *Organization*
| `Default`
|

| *Credential type*
| `Red Hat Ansible Automation Platform`
|

| *Red Hat Ansible Automation Platform*
| `https://control.ansible.workshop/api/controller/`
| Automation ExecutionコンポーネントのURLです。

| *Username*
| `admin`
|

| *Password*
| `ansible123!`
|

| *OAuth token*
|
| _意図的に空欄にしています_

| *Verify SSL*
| チェックを外す
|
|===
+
NOTE: 詳細については、公式ドキュメントを参照してください: link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-set-up-rhaap-credential-type#eda-set-up-rhaap-credential-type[Red Hat Ansible Automation Platform credential].

少し時間を取って新しいUIを見て回り、次のチャレンジに進んでください。

---

== トラブルシューティング

このラボで問題が発生した場合は、こちらへ: link:https://github.com/ansible/workshops/issues
